
steps:
#build the container image
- name: "gcr.io/cloud-builders/docker"
  args: ["build","-t","gcr.io/$PROJECT_ID/gcpdevops","."]
#push container image
- name: "gcr.io/cloud-builders/docker"
  args: ["push", "gcr.io/$PROJECT_ID/gcpdevops"]
#deploy container image to GKE
- name: "gcr.io/cloud-builders/gke-deploy"
  args:
  - run
  - --filename=gke.yaml
  - --image=gcr.io/peaceful-campus-388209/gcpdevops@sha256:e809dff85aa53ee9e33ca0e778122fdb845cd38cca81a8590d5023dc69244ee9
  - --location=us-central1-c
  - --cluster=gcp-devops-project
  - --namespace=gcp-devops-prod