---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: exppresjs
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: exppresjs
    spec:
      containers:
      - name: expressjs
        image: enisaydogan/expressjs:v2
        ports:
        - containerPort: 80
        
  selector:
    matchLabels:
      app: exppresjs
---
apiVersion: v1
kind: Service
metadata:
  name: expressjs
spec:
  type: ClusterIP
  ports:
  - port: 80
  selector:
    app: expressjs