apiVersion: apps/v1
kind: Deployment
metadata:
  name: exppressjs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: expressjs
  template:
    metadata:
      labels:
        app: exppressjs
    spec:
      containers:
      - name: expressjs
        image: gcr.io/peaceful-campus-388209/gcpdevops@sha256:e809dff85aa53ee9e33ca0e778122fdb845cd38cca81a8590d5023dc69244ee9
        ports:
        - containerPort: 5000
        env:
          - name: PORT 
            value: "5000"
