apiVersion: apps/v1
kind: Deployment
metadata:
  name: gcp-devops-gke
spec:
  replicas: 1
  selector:
    matchLabels:
      app: expressjs
  template:
    metadata:
      labels:
        app: expressjs
    spec:
      containers:
      - name: gcp-devops-gke
        image: gcr.io/peaceful-campus-388209/gcpdevops:latest
        ports:
        - containerPort: 5000
        env:
          - name: PORT 
            value: "5000"
