apiVersion: apps/v1
kind: Deployment
metadata:
  name: exppressjs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: expressjs
  template:
    metadata:
      labels:
        app: exppressjs
    spec:
      containers:
      - name: expressjs
        image: gcr.io/$PROJECT_ID/gcpdevops/express.js:latest
        ports:
        - containerPort: 5000
        env:
          - name: PORT 
            value: "5000"
